// File: src/constants/navigation.constants.ts
import { NavItem, TeamMember } from "@/types";

export const NAV_ITEMS: NavItem[] = [
  { id: "inbox", label: "Inbox", href: "/", isActive: true },
  { id: "contacts", label: "Contacts", href: "/contacts" },
  { id: "employees", label: "All employees", href: "/employees" },
  { id: "workflows", label: "Workflows", href: "/workflows" },
  { id: "campaigns", label: "Campaigns", href: "/campaigns" },
];

export const TEAM_MEMBERS: TeamMember[] = [
  {
    id: "sarah",
    userId: "user-sarah",
    name: "Sarah Williams",
    initials: "SW",
    unreadCount: 2,
    online: true,
    role: "Customer Success",
    lastActive: "now",
  },
  {
    id: "michael",
    userId: "user-michael",
    name: "Michael Johnson",
    initials: "MJ",
    unreadCount: 11,
    online: true,
    role: "Product Manager",
    lastActive: "now",
  },
  {
    id: "emily",
    userId: "user-emily",
    name: "Emily Davis",
    initials: "ED",
    unreadCount: 4,
    online: false,
    role: "Support Lead",
    lastActive: "2 hours ago",
  },
  {
    id: "christopher",
    userId: "user-christopher",
    name: "Christopher Miller",
    initials: "CM",
    unreadCount: 4,
    online: true,
    role: "Sales Rep",
    lastActive: "now",
  },
  {
    id: "amanda",
    userId: "user-amanda",
    name: "Amanda Garcia",
    initials: "AG",
    unreadCount: 5,
    online: false,
    role: "Customer Success",
    lastActive: "1 hour ago",
  },
  {
    id: "joshua",
    userId: "user-joshua",
    name: "Joshua Martinez",
    initials: "JM",
    unreadCount: 1,
    online: true,
    role: "Support Agent",
    lastActive: "now",
  },
  {
    id: "ashley",
    userId: "user-ashley",
    name: "Ashley Taylor",
    initials: "AT",
    unreadCount: 1,
    online: false,
    role: "Sales Rep",
    lastActive: "30 mins ago",
  },
  {
    id: "daniel",
    userId: "user-daniel",
    name: "Daniel Anderson",
    initials: "DA",
    unreadCount: 2,
    online: true,
    role: "Support Agent",
    lastActive: "now",
  },
  {
    id: "jessica",
    userId: "user-jessica",
    name: "Jessica Thomas",
    initials: "JT",
    unreadCount: 2,
    online: false,
    role: "Customer Success",
    lastActive: "15 mins ago",
  },
];

export const COLORS = {
  primary: "#007AEC",
  secondary: "#EFF2F2",
  border: "#D8DEE4",
  textSecondary: "#90909B",
  accent: "#FE3265",
} as const;
